<a href="https://colab.research.google.com/github/Maruf0275/Machine-Learning-Notes/blob/main/Pandas/Pandas_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Introduction to Pandas
Pandas is the standard tool for data manipulation in Python.

### Importing Pandas

In [1]:
import numpy as np
import pandas as pd

### Series from lists

In [2]:
# String
country = ['Bangladesh','India','USA','Pakistan','Nepal']
print(pd.Series(country))
animal = ['Tiger','Lion','Elephant','Cat','Dog']
print(pd.Series(animal))

0    Bangladesh
1         India
2           USA
3      Pakistan
4         Nepal
dtype: object
0       Tiger
1        Lion
2    Elephant
3         Cat
4         Dog
dtype: object

In [3]:
# integers
runs = [18,39,49,49,100]
print(pd.Series(runs))

0     18
1     39
2     49
3     49
4    100
dtype: int64

In [4]:
# Custom Index
marks = [50,66,73,80]
subjects = ['Maths','English','Science','Bangla']
print(pd.Series(marks, index = subjects))

Maths      50
English    66
Science    73
Bangla     80
dtype: int64

In [5]:
# Setting a name
marks = [50,66,73,80]
subjects = ['Maths','English','Science','Bangla']

print(pd.Series(marks, index = subjects,name = 'Marks of Maruf'))

Maths      50
English    66
Science    73
Bangla     80
Name: Marks of Maruf, dtype: int64

### Series from dictionary

In [6]:
marks = {
    'Maths':50,
    'English':66,
    'Science':73,
    'Bangla':80
}

print(pd.Series(marks,name = 'Marks of Maruf'))

Maths      50
English    66
Science    73
Bangla     80
Name: Marks of Maruf, dtype: int64

### Series Attribute

In [7]:
# size
marks = {
    'Maths':50,
    'English':66,
    'Science':73,
    'Bangla':80
}
marks_series = pd.Series(marks,name = 'Marks fo Maruf')
print(marks_series.size)

4

In [8]:
# dtype
marks_series.dtype

dtype('int64')

In [9]:
# name
marks_series.name

'Marks fo Maruf'

In [10]:
# is_unique
print(marks_series.is_unique)

pd.Series([1,1,3,4,5]).is_unique

True

False

In [11]:
# index
marks_series.index # Store values in index

Index(['Maths', 'English', 'Science', 'Bangla'], dtype='object')

In [12]:
# values
marks_series.values

array([50, 66, 73, 80])

### Series using read_csv

In [13]:
# with one col
subs = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/subs.csv').squeeze(True)
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [14]:
# with 2 cols
vk = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/kohli_ipl.csv',index_col='match_no').squeeze(True)
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [15]:
movies = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/bollywood.csv',index_col='movie').squeeze(True)
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

### Series Methods

In [16]:
# Head and tail
subs.head()

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [17]:
vk.head(3)

match_no
1     1
2    23
3    13
Name: runs, dtype: int64

In [18]:
vk.tail()

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [19]:
# sample
movies.sample(5)

movie
Teen Thay Bhai             Om Puri
Dhol (film)          Sharman Joshi
Cheeni Kum        Amitabh Bachchan
A Flying Jatt         Tiger Shroff
Shabd (film)           Sanjay Dutt
Name: lead, dtype: object

In [20]:
# value_counts -> movies
movies.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [21]:
# sort_values -> inplace(sort the original vlaue in dataset permanently)
# vk.sort_values(inplace=True)
vk.sort_values(ascending=False).head(5).values

array([113, 109, 108, 100, 100])

In [22]:
# sort_index -> inplace -> movies
# sort_values
movies.sort_values()
movies.sort_index()

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: object

### Series Maths Methods

In [23]:
# cont
vk.count()

np.int64(215)

In [24]:
# sum -> product
subs.sum()

np.int64(49510)

In [25]:
# mean -> median -> mode -> std -> var
print(subs.mean())
print(vk.median())
print(movies.mode())
print(subs.std())
print(subs.var())

135.64383561643837
24.0
0    Akshay Kumar
Name: lead, dtype: object
62.67502303725269
3928.1585127201556

In [26]:
# min/max
subs.max()

396

In [27]:
# describe
vk.describe()

count    215.000000
mean      30.855814
std       26.229801
min        0.000000
25%        9.000000
50%       24.000000
75%       48.000000
max      113.000000
Name: runs, dtype: float64

### Series Indexing

In [28]:
# integer indexing
x = pd.Series([12,13,14,35,46,57,58,79,9])
x[0]

np.int64(12)

In [29]:
# negative indexing(if the index is string)
movies[-1]

/tmp/ipykernel_5912/3884239597.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  movies[-1]

'Akshay Kumar'

In [30]:
# slicing
vk[5:15]

match_no
6      9
7     34
8      0
9     21
10     3
11    10
12    38
13     3
14    11
15    50
Name: runs, dtype: int64

In [31]:
# negative slicing
vk[-5:]

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [32]:
movies[-5:]

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [33]:
# fancy indexing
vk[[1,3,4,6]]

match_no
1     1
3    13
4    12
6     9
Name: runs, dtype: int64

In [34]:
#indexing with labels -> fancy indexing
movies['Uri: The Surgical Strike']
movies['Why Cheat India']

'Emraan Hashmi'